spring:
  datasource:
    username: root
    password: WKQ!123!wkq
    url: jdbc:mysql://172.18.9.173:3306/galaxy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
fdfs:
  soTimeout: 2000 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  reqHost: 112.74.161.190   #nginx访问地址
  reqPort: 80              #nginx访问端口
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 172.18.9.173:22122