server:
  port: 8090
spring:
  redis:
    database: 0
    host: 112.74.161.190
    port: 6379
    timeout: 1000
    password: 123456
    jedis:
      pool:
        max-wait: -1
        max-active: 22
        min-idle: 0
  servlet:
    # 文件上传大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      select-strategy: not_empty

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

