server:
  port: 8090
spring:
  redis:
    database: 0
    host: 112.74.161.190
    port: 6379
    timeout: 1000
    password: 123456
    jedis:
      pool:
        max-wait: -1
        max-active: 22
        min-idle: 0
  servlet:
    # 文件上传大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      select-strategy: not_empty

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
# 分布式文件系统FDFS配置
#fdfs:
#  soTimeout: 2000 #socket连接超时时长
#  connectTimeout: 600 #连接tracker服务器超时时长
#  reqHost: 112.74.161.190   #nginx访问地址
#  reqPort: 80              #nginx访问端口
#  thumbImage: #缩略图生成参数，可选
#    width: 150
#    height: 150
#  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
#    - 112.74.161.190:22122
